# Generated by Django 4.2.6 on 2023-11-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('DRK', 'Dark'), ('DRG', 'Dragon'), ('ELC', 'Electric'), ('FRY', 'Fairy'), ('FGT', 'Fighting'), ('FIR', 'Fire'), ('FLY', 'Flying'), ('GHS', 'Ghost'), ('GRS', 'Grass'), ('GRD', 'Ground'), ('ICE', 'Ice'), ('NML', 'Normal'), ('PSN', 'Poison'), ('PSY', 'Psychic'), ('RCK', 'Rock'), ('STL', 'Steel'), ('WTR', 'Water')], default='NML', max_length=3),
        ),
    ]
